import type { CSSProperties } from "react";

export const s = {
  page: { padding: "20px 28px 40px", maxWidth: 880, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", justifyContent: "space-between", gap: 20, alignItems: "flex-start", marginBottom: 18 } satisfies CSSProperties,
  title: { margin: 0, fontSize: 22, lineHeight: 1.25, letterSpacing: "-0.03em", fontWeight: 700 } satisfies CSSProperties,
  subtitle: { margin: "3px 0 0", color: "var(--text-secondary)", fontSize: 13 } satisfies CSSProperties,
  actions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" } satisfies CSSProperties,
  toolbar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, flexWrap: "wrap", marginBottom: 16 } satisfies CSSProperties,
  toolbarLeft: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  acceptedCount: { color: "var(--text-muted)", fontSize: 12 } satisfies CSSProperties,
  filterBar: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap", margin: "-4px 0 12px" } satisfies CSSProperties,
  list: { display: "grid", gap: 12 } satisfies CSSProperties,
  card: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 150px", gap: 14, padding: 16, background: "var(--bg-elevated)", border: "1px solid var(--border)", borderRadius: 9 } satisfies CSSProperties,
  cardAccepted: { borderLeft: "3px solid var(--ok)" } satisfies CSSProperties,
  rule: { margin: 0, fontSize: 14, lineHeight: 1.4, fontWeight: 600, fontStyle: "italic" } satisfies CSSProperties,
  rationale: { margin: "8px 0 12px", color: "var(--text-secondary)", fontSize: 12.5, lineHeight: 1.5 } satisfies CSSProperties,
  category: { marginTop: 8 } satisfies CSSProperties,
  evidence: { marginTop: 10, padding: 0, background: "var(--bg-surface)", border: "1px solid var(--border)", borderRadius: 7, overflow: "hidden" } satisfies CSSProperties,
  evidenceTop: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, minHeight: 28, padding: "5px 10px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  snippet: { margin: 0, padding: "10px 12px", overflowX: "auto", color: "var(--text-primary)", fontSize: 11.5, lineHeight: 1.55, fontFamily: "var(--font-mono)" } satisfies CSSProperties,
  cardActions: { display: "flex", flexDirection: "column", gap: 7, minWidth: 150 } satisfies CSSProperties,
  confidence: { display: "flex", alignItems: "center", gap: 8, marginTop: 10, maxWidth: 300 } satisfies CSSProperties,
  confidenceLabel: { color: "var(--text-muted)", fontSize: 11 } satisfies CSSProperties,
  confidenceBar: { width: 90, flexShrink: 0 } satisfies CSSProperties,
  edit: { display: "grid", gap: 10 } satisfies CSSProperties,
  chips: { display: "flex", gap: 6, flexWrap: "wrap" } satisfies CSSProperties,
  banner: { display: "flex", alignItems: "flex-start", gap: 9, padding: "10px 13px", border: "1px solid rgba(59, 130, 246, 0.2)", borderRadius: 8, background: "var(--accent-bg)", color: "var(--text-secondary)", lineHeight: 1.5, fontSize: 13, marginBottom: 18 } satisfies CSSProperties,
  modalBody: { padding: "18px 22px 8px" } satisfies CSSProperties,
  modalGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 } satisfies CSSProperties,
  editor: { border: "1px solid var(--border)", borderRadius: 8, overflow: "hidden", background: "var(--bg-surface)" } satisfies CSSProperties,
  editorHeader: { display: "flex", alignItems: "center", gap: 8, minHeight: 40, padding: "0 12px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  editorFile: { display: "flex", alignItems: "center", gap: 8, minWidth: 0, fontSize: 12, fontWeight: 600 } satisfies CSSProperties,
  editorBadge: { padding: "2px 6px", borderRadius: 5, background: "var(--bg-hover)", color: "var(--text-muted)", fontSize: 11, fontWeight: 500 } satisfies CSSProperties,
  editorCount: { marginLeft: "auto", color: "var(--text-muted)", fontSize: 11 } satisfies CSSProperties,
  editorSurface: { display: "grid", gridTemplateColumns: "32px minmax(0, 1fr)", minHeight: 460 } satisfies CSSProperties,
  editorLines: { padding: "10px 8px 10px 0", borderRight: "1px solid var(--border)", color: "var(--text-muted)", fontSize: 12.5, lineHeight: "21px", textAlign: "right", userSelect: "none" } satisfies CSSProperties,
  editorTextarea: { width: "100%", minHeight: 460, resize: "vertical", padding: "10px 12px", border: 0, outline: 0, background: "transparent", color: "var(--text-primary)", fontFamily: "var(--font-mono)", fontSize: 12.5, lineHeight: "21px" } satisfies CSSProperties,
  editorPreview: { minHeight: 460, maxHeight: 560, overflow: "auto", padding: "12px 14px", background: "var(--bg-surface)" } satisfies CSSProperties,
  modalFooter: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 } satisfies CSSProperties,
  modalFooterStatus: { color: "var(--text-muted)", fontSize: 12 } satisfies CSSProperties,
} as const;
