import type { CSSProperties } from "react";

export const s = {
  card: (active: boolean, enabled: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 7,
    padding: 11,
    marginTop: 8,
    borderRadius: 8,
    cursor: "pointer",
    border: "1px solid " + (active ? "var(--border-strong)" : "var(--border)"),
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: enabled ? 1 : 0.6,
    minWidth: 0,
  }),
  header: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  iconBox: (color: string, background: string): CSSProperties => ({
    width: 24,
    height: 24,
    borderRadius: 6,
    background,
    color,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  name: {
    flex: 1,
    minWidth: 0,
    padding: 0,
    border: "none",
    background: "none",
    color: "inherit",
    cursor: "pointer",
    fontSize: 12.5,
    fontWeight: 600,
    textAlign: "left",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  description: {
    margin: 0,
    color: "var(--text-muted)",
    fontSize: 12,
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  badges: { display: "flex", alignItems: "center", gap: 5, minWidth: 0, overflow: "hidden" } satisfies CSSProperties,
} as const;
